### ISSUE TITLE
It is not working

### ISSUE THREAD

**Issue by rajcharanthecoder** [swseverance/LeetCodeRatingsTexter#2]
I am from India and the message isn't even delivered

**Comment by swseverance** [comment]
Thanks for raising. I think I resolved the issue and see a message with your rating was just delivered.

**Comment by swseverance** [comment]
You'll get another message with your rating in a few days when it's updated by LeetCode

**Comment by swseverance** [comment]
Please note, if your cell phone carrier does not allow you to send text messages to the United States then the app won't work. I'm trying to get an India cell phone number for users within India to use.
